### ISSUE TITLE
Port pedalpi-dev-platform to Hardkernel Odroid-C2, Amlogic meson GXBB S905

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/pedalpi-dev-platform#10]
I would like to get some support on how to port pedalpi-dev-platform to Hardkernel Odroid-C2 with Amlogic meson64 GXBB S905 processor.
I have a mainline Linux Kernel 5.6 working with ALSA audio working: aplay and arecord. 
A custom daughterboard to emulate MOD DUO with same codec CS4245, 4 mono jacks (Input-L/R, Output L/R), UART connected to MIDI-In/Out, Stereo Headphones.
I have dedicated GPIOs to reset codec, change Input impedance, Input Gain, Headphones Enable/Volume, relays to bypass Left/Right channels, similar to MOD DUO.
 RPi.GPIO has been already ported to Odroid-C2.
Those dedicated GPIOs are managed by codec driver. Should those dedicated GPIOs be controlled by RPi.GPIO instead?
GPIOs for 3PDT switch and knobs are not used yet and I guess they should be managed by RPi.GPIO.
I would need some guidance to point me to the yocto recipes that need to be modified.
I guess that meta-raspberry recipes can be replaced by existing meta-meson recipes.
I would appreciate if you could contact me by email, available on my github profile.

**Comment by auto3000** [comment]
A lot of info below.

> A custom daughterboard to emulate MOD DUO with same codec CS4245, 4 mono jacks (Input-L/R, Output L/R), UART connected to MIDI-In/Out, Stereo Headphones.

Oh really, you did it ? Your blog looks excellent, I liked to read such stuffs in the past and I'm surprised to discover yours just now. I'm impressed by the quality of your products. I should have done a blog like this to describe an how-to of pedalpi, but well, I'm unable to do that. I do project then I switch without any sharing/communication. J'étais parisien aussi lorsque je faisais mes pédales.

> Those dedicated GPIOs are managed by codec driver. Should those dedicated GPIOs be controlled by RPi.GPIO instead?
No, not necessarily. 

> GPIOs for 3PDT switch and knobs are not used yet and I guess they should be managed by RPi.GPIO.
Correct, Rpi.GPIO is only used in pedalpi-dev-platform to get buttons status attached to the GPIOs. But really, I used this library because this was available on Raspberry, and later then I did a port to NanoPI to keep compatibility, but you can rewrite the "button manager".... The button manager is there https://github.com/auto3000/pedalpii/blob/master/pedalpII/main.py

This python script uses RPI.GPIO to read buttons, display stuffs to LCD screen and... send commands (next effect, previous effect) to the mod-duo software. You can fork this, create a new recipe, and reuse all the communication part to mod-duo software and use your own GPIO API to the codec driver.

> I have a mainline Linux Kernel 5.6 working with ALSA audio working: aplay and arecord.
Worth to mention... You may have to tune the software buffer size of the driver (in kernel) to obtain best latency (order of few microseconds... 4us on NanoPI for reference) But this is near useless if you only plan to use delay effects :)

> I guess that meta-raspberry recipes can be replaced by existing meta-meson recipes.
No, just add meta-meson to the super project pedalpi-dev-platform  at the same level as meta-nanopi and the init.sh file will select the proper board "layer".
The yocto release is morty. You may want to upgrade to newer release but really, this does not merit any effort except if you find a major package problem, or a kernel problem in the version pointed by the recipe.

Modify the https://github.com/auto3000/pedalpi-dev-platform/blob/master/init.sh to clone your meta-meson layer.

Create a directory in pedalpi-dev-platform/platforms/meta-odroid-c2 (or meson?) to store all the hacks you will need.... like the kernel configuration and so on. The  nanopi directory will give you an idea of all problems you can meet .

Create two conf files for the odroid-c2, see https://github.com/auto3000/pedalpi-dev-platform/blob/master/pedalpi-src-build/conf/templates/nanopi-neo-air.bblayers.conf and https://github.com/auto3000/pedalpi-dev-platform/blob/master/pedalpi-src-build/conf/templates/nanopi-neo-air.local.conf

You also need to create a new recipe for the new software to control buttons... the recipe at https://github.com/auto3000/meta-pedalpi/blob/master/recipes-core/pedalpii/pedalpii.bb can be took as example.

> I would appreciate if you could contact me by email, available on my github profile.
I send this in an email copy...
